site_name: OWASP Top 10:2025
site_description: OWASP Top 10:2025
site_url: https://owasp.org/Top10/2025/
repo_name: OWASP/Top10
repo_url: https://github.com/OWASP/Top10
copyright: © Copyright 2021-2025 - OWASP Top 10 Team - This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/3.0/deed.en_US">Creative Commons Attribution 3.0 Unported License</a>.
docs_dir: docs
theme:
  name: material
  language: en
  logo: assets/OWASP_Logo_Transp.png
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest

nav:
  - Home: 'en/index.md'
  - Introduction: 'en/0x00_2025-Introduction.md'
  - About OWASP: 'en/0x01_2025-About_OWASP.md'
  - What are Application Security Risks?: 'en/0x02_2025-What_are_Application_Security_Risks.md'
  - Establishing a Modern Application Security Program: 'en/0x03_2025-Establishing_a_Modern_Application_Security_Program.md'
  - Top 10:2025 List:
    - A01 Broken Access Control: 'en/A01_2025-Broken_Access_Control.md'
    - A02 Security Misconfiguration: 'en/A02_2025-Security_Misconfiguration.md'
    - A03 Software Supply Chain Failures: 'en/A03_2025-Software_Supply_Chain_Failures.md'
    - A04 Cryptographic Failures: 'en/A04_2025-Cryptographic_Failures.md'
    - A05 Injection: 'en/A05_2025-Injection.md'
    - A06 Insecure Design: 'en/A06_2025-Insecure_Design.md'
    - A07 Authentication Failures: 'en/A07_2025-Authentication_Failures.md'
    - A08 Software or Data Integrity Failures: 'en/A08_2025-Software_or_Data_Integrity_Failures.md'
    - A09 Security Logging and Alerting Failures: 'en/A09_2025-Security_Logging_and_Alerting_Failures.md'
    - A10 Mishandling of Exceptional Conditions: 'en/A10_2025-Mishandling_of_Exceptional_Conditions.md'
  - Next Steps: 'en/X01_2025-Next_Steps.md'

markdown_extensions:
  - attr_list

plugins:
  - search
  - i18n:
      default_language: en
      docs_structure: folder
      material_alternate: true
      reconfigure_material: true
      languages:
        - locale: en
          default: true
          name: en - English
          build: true
        - locale: ko
          name: ko - 한국어
          build: true
          nav_translations:
            Home: 홈
            Introduction: 소개
            About OWASP: OWASP 소개
            What are Application Security Risks?: 애플리케이션 보안 위험이란 무엇인가?
            Establishing a Modern Application Security Program: 현대적 애플리케이션 보안 체계를 수립하는 법
            Top 10:2025 List: OWASP Top 10:2025 목록
            A01 Broken Access Control: A01 불충분한 접근 제어
            A02 Security Misconfiguration: A02 보안 설정 오류
            A03 Software Supply Chain Failures: A03 소프트웨어 공급망 실패
            A04 Cryptographic Failures: A04 암호 실패
            A05 Injection: A05 인젝션
            A06 Insecure Design: A06 안전하지 않은 설계
            A07 Authentication Failures: A07 인증 실패
            A08 Software or Data Integrity Failures: A08 소프트웨어 또는 데이터 무결성 실패
            A09 Security Logging and Alerting Failures: A09 보안 로깅 및 알림 실패
            A10 Mishandling of Exceptional Conditions: A10 부적절한 예외 처리
            Next Steps: 다음 단계
      nav_translations:

        SAMPLE:
          Home: Startseite
          Notice: Anmerkung
          Introduction: Einführung
          How to use the OWASP Top 10 as a standard: Wie man die OWASP Top 10 als Standard verwendet
          How to start an AppSec program with the OWASP Top 10: Wie man ein AppSec-Program mit den OWASP Top 10 beginnt
          About OWASP: Über OWASP
          Top 10:2025 List: Liste der Top 10:2025
          A01 Broken Access Control: A01 - Mangelhafte Zugriffskontrolle
          A02 Cryptographic Failures: A02 - Fehlerhafter Einsatz von Kryptographie
          A03 Injection: A03 - Injection
          A04 Insecure Design: A04 - Unsicheres Anwendungsdesign
          A05 Security Misconfiguration: A05 - Sicherheitsrelevante Fehlkonfiguration
          A06 Vulnerable and Outdated Components: A06 - Unsichere oder veraltete Komponenten
          A07 Identification and Authentication Failures: A07 - Fehlerhafte Authentifizierung
          A08 Software and Data Integrity Failures: A08 - Fehlerhafte Prüfung der Software- und Datenintegrität
          A09 Security Logging and Monitoring Failures: A09 - Unzureichendes Logging und Sicherheitsmonitoring
          A10 Server Side Request Forgery (SSRF): A10 - Server-Side Request Forgery (SSRF)
          Next Steps: Nächste Schritte
  - macros:     # needs to be the last plugin to export the final osib-YAML file for all languages
      module_name: '../osib/osib_macro'
      include_dir: '../osib/include'
      verbose: false                                                  # debug
      on_error_fail: true
extra:
  alternate:                                                         # see https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language-selector
    - name: en - English
      link: ./en/
      lang: en
    - name: ko - Korean
      link: ./ko/
      lang: ko
#    - name: de - Deutsch
#      link: ./de/
#      lang: de
  osib:
    document:     osib.owasp.top10
    version:      2025-0-1
#    document:     <osib-id>                    # e.g. osib.owasp.top10
#    version:      <version-no, no dots '.'>    # e.g. 4-0, 2025-1-0
    categories:   [document, awareness]        # list of all default categories
    default_lang: en
    yaml_file:    ../osib/include/osib.yml
    export_dir:   ../osib/export
    latest:       2                            # 2: add the latest version(s), if successor(s) exist, log an info
    debug:        0                            # debug level (0-3); default is 2
    cre:          osib.owasp.cre.1-0
    successor_texts:
      en:         successor
      de:         Nachfolger
    split_to_texts:
      en:         split to
      de:         Aufgeteilt in
